import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Layout';
import Navbar from '../components/Navbar';
import { Box, Typography } from '@mui/material';
import ScriptInput from '../components/Inputs/ScriptInput';

const CreateVideo: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isCreateVideo />
      <main>
        <Layout>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              width: '100%',
            }}
          >
            <Box>
              <Typography variant="h1">
                Create Your Slideshow Video
                <br />{' '}
                <Box component="span" sx={{ color: 'primary.main' }}>
                  In 3 Easy Steps
                </Box>
              </Typography>
              <Typography variant="subtitle1">
                First time using WriteMyVideo? Check out our tutorial!
              </Typography>
            </Box>
            <Box>
              <ScriptInput />
            </Box>
          </Box>
        </Layout>
      </main>
    </div>
  );
};

export default CreateVideo;
